# Generated by Django 3.2 on 2021-05-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
