# Generated by Django 3.2 on 2021-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userchat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
