# Generated by Django 3.2.2 on 2021-05-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210526_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emitter',
        ),
        migrations.AddField(
            model_name='message',
            name='emitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
