# Generated by Django 3.2 on 2021-05-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userchat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userchat',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
