# Generated by Django 3.2.2 on 2021-05-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210526_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_1',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_1',
            field=models.ManyToManyField(related_name='user_1', to='api.User'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_2',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_2',
            field=models.ManyToManyField(related_name='user_2', to='api.User'),
        ),
    ]
