# Generated by Django 3.2.2 on 2021-05-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210526_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_1',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='api.user'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_2',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='api.user'),
        ),
    ]
