# Generated by Django 3.2.2 on 2021-05-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userchat',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userchat',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
