# Generated by Django 3.2.2 on 2021-05-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210516_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
