# Generated by Django 3.2.2 on 2021-05-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userchat_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
