# Generated by Django 3.2.2 on 2021-05-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_userchat_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
