# Generated by Django 3.2.2 on 2021-05-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='public_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
