# Generated by Django 3.2.2 on 2021-05-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_avatar_public_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='AvatarModel',
        ),
    ]
