# Generated by Django 3.2.2 on 2021-05-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_avatar_avatarmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatarmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='userchat',
            name='avatar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='api.avatarmodel'),
        ),
    ]
