# Generated by Django 3.2.2 on 2021-05-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210522_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='api.avatarmodel'),
        ),
    ]
