# Generated by Django 3.2.2 on 2021-05-23 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='messages',
            field=models.ManyToManyField(to='api.MessageModel'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='last_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_message', to='api.messagemodel'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
