# Generated by Django 3.2.2 on 2021-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210523_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
